# Copyright (c) 2025, Frappe Technologies Pvt Ltd and contributors
# For license information, please see license.txt

"""
Menu integration utilities for auto-populating Website Header Footer Config
when pages are generated by AI or manually created.
"""

import frappe
from frappe import _


def update_menu_after_page_creation(page_doc, add_to_menu: bool = True):
	"""
	Update the Website Header Footer Config menu after a Builder Page is created.

	Args:
		page_doc: The Builder Page document
		add_to_menu: Whether to add this page to the menu

	Returns:
		dict: The added menu item or None
	"""
	if not add_to_menu:
		return None

	try:
		config = frappe.get_single("Website Header Footer Config")
	except frappe.DoesNotExistError:
		# Config doesn't exist yet, nothing to update
		return None

	if not config.menu_items:
		config.menu_items = []

	# Don't add if already exists
	url = f"/{page_doc.route}" if page_doc.route else "/"
	for item in config.menu_items:
		if item.url == url:
			return None

	label = page_doc.page_title or page_doc.page_name

	config.append("menu_items", {
		"label": label,
		"url": url,
		"is_external": False,
		"open_in_new_tab": False,
	})
	config.save(ignore_permissions=True)

	return {
		"label": label,
		"url": url,
	}


def update_menu_from_generated_pages(pages: list[dict]):
	"""
	Update menu with multiple pages at once.

	Args:
		pages: List of page info dicts with keys:
			- title: Page title
			- route: Page route
			- add_to_menu: Whether to add to menu (default True)
			- menu_label: Optional custom menu label

	Returns:
		list: Added menu items
	"""
	try:
		config = frappe.get_single("Website Header Footer Config")
	except frappe.DoesNotExistError:
		return []

	added = []

	for page in pages:
		if not page.get("add_to_menu", True):
			continue

		url = f"/{page['route']}" if page.get("route") else "/"

		# Skip if already exists
		if any(item.url == url for item in (config.menu_items or [])):
			continue

		label = page.get("menu_label") or page.get("title", "Page")

		config.append("menu_items", {
			"label": label,
			"url": url,
			"is_external": False,
			"open_in_new_tab": False,
		})
		added.append({"label": label, "url": url})

	if added:
		config.save(ignore_permissions=True)

	return added


def sync_menu_with_pages(replace: bool = False):
	"""
	Synchronize menu items with published Builder Pages.

	Args:
		replace: If True, replace all menu items; if False, only add missing

	Returns:
		dict: Summary of changes
	"""
	try:
		config = frappe.get_single("Website Header Footer Config")
	except frappe.DoesNotExistError:
		return {"error": "Website Header Footer Config not found"}

	pages = frappe.get_all(
		"Builder Page",
		filters={"published": 1},
		fields=["name", "page_title", "route"],
		order_by="modified desc"
	)

	if replace:
		config.menu_items = []

	added = []
	skipped = []

	existing_urls = {item.url for item in (config.menu_items or [])}

	for page in pages:
		url = f"/{page.route}" if page.route else "/"

		if url in existing_urls:
			skipped.append(url)
			continue

		label = page.page_title or page.name
		config.append("menu_items", {
			"label": label,
			"url": url,
			"is_external": False,
			"open_in_new_tab": False,
		})
		added.append(url)
		existing_urls.add(url)

	if added or replace:
		config.save(ignore_permissions=True)

	return {
		"added": added,
		"skipped": skipped,
		"total_menu_items": len(config.menu_items or []),
	}


def get_site_type_menu_defaults(site_type: str) -> list[dict]:
	"""
	Get default menu items for a site type.

	Args:
		site_type: Type of site (vitrine, ecommerce, blog, etc.)

	Returns:
		list: Default menu items
	"""
	DEFAULTS = {
		"vitrine": [
			{"label": _("Home"), "url": "/"},
			{"label": _("About"), "url": "/about"},
			{"label": _("Services"), "url": "/services"},
			{"label": _("Contact"), "url": "/contact"},
		],
		"ecommerce": [
			{"label": _("Home"), "url": "/"},
			{"label": _("Shop"), "url": "/all-products"},
			{"label": _("Categories"), "url": "/shop-by-category"},
			{"label": _("About"), "url": "/about"},
			{"label": _("Contact"), "url": "/contact"},
		],
		"blog": [
			{"label": _("Home"), "url": "/"},
			{"label": _("Blog"), "url": "/blog"},
			{"label": _("About"), "url": "/about"},
			{"label": _("Contact"), "url": "/contact"},
		],
		"portfolio": [
			{"label": _("Home"), "url": "/"},
			{"label": _("Work"), "url": "/work"},
			{"label": _("About"), "url": "/about"},
			{"label": _("Contact"), "url": "/contact"},
		],
		"saas": [
			{"label": _("Home"), "url": "/"},
			{"label": _("Features"), "url": "/features"},
			{"label": _("Pricing"), "url": "/pricing"},
			{"label": _("About"), "url": "/about"},
			{"label": _("Contact"), "url": "/contact"},
		],
	}

	return DEFAULTS.get(site_type, DEFAULTS["vitrine"])
